### PR TITLE
Upgrade to Dropwizard 9.1

### PR DESCRIPTION
**Pull request by toshipiazza**
- Updates AdPrincipal to implement Principal interface
- Updates README example
- Updates sample-service for 9.1, also adds CachingAuthenticator, as in README

### CODE REVIEW

**Comment by gavinhogan** [comment]
Is this backwards compatible with 0.7?

**Comment by toshipiazza** [comment]
I will test it out to make sure, but I believe so. We only make AdPrincipal implement Principal, but in Dropwizard 7 a principal can be of any type.

**Comment by toshipiazza** [comment]
Actually just tested it out, dropwizard 7 includes `org.apache.commons.lang`, but in dropwizard 9 this is renamed (?) to `org.apache.commons.lang3`, as we can see in the commit. I'll try to see if this problem can be fixed.

**Comment by toshipiazza** [comment]
It was decided that we should just move to the 0.3.x major version and notify in the README how to go about using the library across different dropwizard versions.

**Comment by gavinhogan** [comment]
Looks good - will push a release today.

**Pull request merged**
